from requests.adapters import HTTPAdapter
from typing import Any

class Pkcs12Adapter(HTTPAdapter):
    ssl_context: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def init_poolmanager(self, *args: Any, **kwargs: Any): ...
    def proxy_manager_for(self, *args: Any, **kwargs: Any): ...
